site_name: Docs
theme:
  name: material
  custom_dir: ../../overrides/
  logo: assets/images/logos/fl.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: darkmode
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: es
  features:
    - navigation.path
    #- navigation.tabs # Top tabs (like Ionic)
    - navigation.expand # Expanded sections in sidebar
    - navigation.sections # Section headers in sidebar
    - navigation.instant # Instant page loading (SPA-like)
    - navigation.tracking # Track active section in sidebar
    - navigation.top # Track active section in sidebar
    - search.highlight # Highlight search terms
    - search.suggest # Show search suggestions
    - content.code.copy  # Code copy button
use_directory_urls: true
extra:
  alternate:
    - name: English
      link: /docs/
      lang: en
    - name: Espa√±ol
      link: /docs/es
      lang: es
extra_css:
  - assets/stylesheets/extra.css
docs_dir: ../../docs/es
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences