site_name: Docs
theme:
  name: material
  custom_dir: ./overrides/
  logo: assets/images/logos/fl.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: darkmode
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode
  language: en
  features:
    - navigation.path
    #- navigation.tabs # Top tabs (like Ionic)
    - navigation.expand # Expanded sections in sidebar
    - navigation.sections # Section headers in sidebar
    - navigation.instant # Instant page loading (SPA-like)
    - navigation.tracking # Track active section in sidebar
    - navigation.top # Track active section in sidebar
    #- header.autohide # Auto-hide header on scroll down
    - search.highlight # Highlight search terms
    - search.suggest # Show search suggestions
    - content.code.copy  # Code copy button
use_directory_urls: true
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
  - stylesheets/custom-components.css
  - stylesheets/404-error.css
  - stylesheets/components/fh-codemodal.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/components/flx-navbutton.js
  - javascripts/components/fh-codemodal.js
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      pygments_style: monokai
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Espa√±ol
          build: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
        - not-zoomable